[build]
  dir = "clientfrontend"     
  command = "npm run build"  
  publish = "clientfrontend/build" 

[[build]]
  functions = "backeneddata/functions"  
  deploy = { command = "netlify deploy --prod" }


 