[build]
  dir = "clientfrontend"     
  command = "npm run build"  
  publish = "clientfrontend/build" 

[[build]]
  functions = "/Users/suresh/Desktop/RoseMaryReactApps/ClientsideBIGBASKETapp/ReactBigBasketApp/backeneddata/functions"  
  deploy = { command = "netlify deploy --prod" }


 