[build]
  dir = "clientfrontend"
  command = "npm run build"
  publish = "clientfrontend/build"

[build.environment]
  FUNCTIONS_DIR = "backeneddata/functions" # Define the directory for serverless functions

[deploy]
  command = "netlify deploy --prod"



 