[build]
  dir = "clientfrontend"     
  command = "npm run build"  
  publish = "clientfrontend/build" 

  command = "npm start"  
  publish = "backeneddata/dist"  
  functions = "functions"  
  deploy = { command = "netlify deploy --prod" }


 