[build]
  command = "cd clientfrontend && npm run build"  # Change directory to frontend and run build
  publish = "clientfrontend/build"       
  functions = "backeneddata/functions" 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

