[build]
  command = "npm run build"        
  publish = "clientfrontend/build"       
  functions = "backeneddata/functions" 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200